services:
  batch-automation-prod:
    image: batch-automation:${VERSION:-latest}
    ports:
      - "5000:8000"
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - ROOT_PATH=/v1/batch
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    networks:
      - batch-redis
    restart: unless-stopped

networks:
  batch-redis:
    external: true
